#pragma once
#ifndef _RESOURCES_H

#define WINDOW_CLASS_NAME			L"Homework 01"
#define WINDOW_TITLE				L"Homework 01"

#define BACKGROUND_COLOR			D3DCOLOR_XRGB(200, 200, 255)
#define SCREEN_WIDTH				640
#define SCREEN_HEIGHT				480

#define MAX_FRAME_RATE				90

#define ID_TEXTURES_PLAYER			0
#define ID_TEXTURES_NPC				1

#define MARIO_TEXTURE_PATH			L"resources//mario.png"

#define PLAYER_START_X				SCREEN_WIDTH / 2 - 50
#define PLAYER_START_Y				SCREEN_HEIGHT / 2 - 50
#define PLAYER_WIDTH				30
#define PLAYER_HEIGHT				32
#define PLAYER_WALKING_SPEED		0.1f

#define PLAYER_STATE_IDLE			0
#define PLAYER_STATE_MOVING_RIGHT	100
#define PLAYER_STATE_MOVING_LEFT	200
#define PLAYER_STATE_MOVING_UP		300
#define PLAYER_STATE_MOVING_DOWN	400

#define PLAYER_ANIMATION_IDLE_RIGHT			0
#define PLAYER_ANIMATION_IDLE_LEFT			1
#define PLAYER_ANIMATION_IDLE_UP			2
#define PLAYER_ANIMAION_IDLE_DOWN			3	
#define PLAYER_ANIMATION_MOVING_RIGHT		4
#define PLAYER_ANIMATION_MOVING_LEFT		5
#define PLAYER_ANIMATION_MOVING_UP			6
#define PLAYER_ANIMATION_MOVING_DOWN		7

#define NPC_ANIMATION_MOVING_RIGHT		0
#define NPC_ANIMATION_MOVING_LEFT		1
#define NPC_ANIMATION_MOVING_UP			2
#define NPC_ANIMATION_MOVING_DOWN		3


#define DIRECTINPUT_VERSION			0x0800
#define KEYBOARD_BUFFER_SIZE		1024

#endif // !_RESOURCES_H

